export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_PORTFOLIO_INFO = "SET_PORTFOLIO_INFO";
export const SET_PROJECTS_INFO = "SET_PROJECTS_INFO";

